version: '3.0'  
  
services:  
  db:  
    build: ./1 - Database  
    environment:  
      MYSQL_DATABASE: opa  
      MYSQL_ROOT_PASSWORD: temp123
    ports:  
      - "3306:3306"
    healthcheck:  
      test: ["CMD-SHELL", "mysql --user=root --password=temp123 --execute='SELECT 1'"]  
      interval: 10s  
      timeout: 5s  
      retries: 3 
      start_period: 10s 

      
  datascripts:  
    build: ./2 - BinanceDataScripts  
    depends_on:  
      db:
        condition: service_healthy
    healthcheck:  
      test: ["CMD-SHELL", "curl --fail -s http://localhost:9000/healthcheck"]  
      interval: 20s  
      timeout: 10s  
      retries: 5 
      start_period: 20s 
    ports:
     - "9000:9000" 
    environment:  
      MYSQL_HOST: db  
      MYSQL_DATABASE: opa
      MYSQL_PASSWORD: temp123

  api:  
    build: ./3 - trainData  
    depends_on: 
      datascripts:
       condition: service_healthy
      db:
       condition: service_healthy    
    ports:
     - "8000:8000" 
    healthcheck:  
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8000/docs"]  
      interval: 20s  
      timeout: 10s  
      retries: 5 
      start_period: 5s 
    environment:  
      MYSQL_HOST: db  
      MYSQL_DATABASE: opa
      MYSQL_PASSWORD: temp123

  airflow:
    build: ./4 - Airflow  
    depends_on: 
      api:
       condition: service_healthy   
    ports:
     - "8080:8080" 
     - "9090:9090" 
    environment:  
      API_HOST: api
      API_USERNAME: slebib
      API_PASSWORD: temp123