version: '3.0'  
  
services:  
  db:  
    build: ./1 - Database  
    environment:  
      MYSQL_DATABASE: opa  
      MYSQL_ROOT_PASSWORD: temp123
    ports:  
      - "3306:3306"
    network_mode: "host" 
    healthcheck:  
      test: ["CMD-SHELL", "mysql --user=root --password=temp123 --execute='SELECT 1'"]  
      interval: 10s  
      timeout: 5s  
      retries: 3  
    networks:
      - mynetwork
  
  datascripts:  
    build: ./2 - BinanceDataScripts  
    depends_on:  
      db:
        condition: service_healthy
    healthcheck:  
      test: ["CMD-SHELL", "curl --fail -s http://localhost:9000/healthcheck"]  
      interval: 10s  
      timeout: 5s  
      retries: 3  
    ports:
     - "9443:9443"  
     - "443:443" 
     - "9000:9000" 
    environment:  
      MYSQL_HOST: db  
      MYSQL_DATABASE: opa
      MYSQL_PASSWORD: temp123
    networks:
      - mynetwork
  
  api:  
    build: ./3 - trainData  
    depends_on: 
      datascripts:
       condition: service_healthy
      db:
       condition: service_healthy    
    ports:
     - "8000:8000" 
    environment:  
      MYSQL_HOST: db  
      MYSQL_DATABASE: opa
      MYSQL_PASSWORD: temp123
    networks:
      - mynetwork
networks:  
  mynetwork:  
    driver: bridge  
    ipam:  
      driver: default  
      config:  
        - subnet: 192.168.0.0/24  